services:
  - type: web
    name: innovationhub
    runtime: python
    pythonVersion: 3.14.2
    build:
      command: pip install -r requirements.txt
    start: bash build.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.14.2
